spring.application.name=skejac

spring.servlet.context-path=/skejac/api

spring.datasource.url=jdbc:mysql://localhost:3306/skejac_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev
